


INSERT INTO [Consultorios].[dbo].[Alergia] VALUES (1,'NA')
INSERT INTO [Consultorios].[dbo].[Alergia] VALUES (2,'Polen')
INSERT INTO [Consultorios].[dbo].[Alergia] VALUES (3,'Acaros')
INSERT INTO [Consultorios].[dbo].[Alergia] VALUES (4,'Polvo')
INSERT INTO [Consultorios].[dbo].[Alergia] VALUES (5,'Penicilina')
INSERT INTO [Consultorios].[dbo].[Alergia] VALUES (6,'Aspirina')
INSERT INTO [Consultorios].[dbo].[Alergia] VALUES (7,'Lactosa')
INSERT INTO [Consultorios].[dbo].[Alergia] VALUES (8,'Gluten')


INSERT INTO [Consultorios].[dbo].[Pais] VALUES (1,'Chile')
INSERT INTO [Consultorios].[dbo].[Pais] VALUES (2,'Argentina')
INSERT INTO [Consultorios].[dbo].[Pais] VALUES (3,'Brazil')
INSERT INTO [Consultorios].[dbo].[Pais] VALUES (4,'Mexico')

INSERT INTO [Consultorios].[dbo].[Region] VALUES (1,'Metropolitana',1)

INSERT INTO [Consultorios].[dbo].[Provincia] VALUES (1,'Santiago',1)
INSERT INTO [Consultorios].[dbo].[Provincia] VALUES (2,'Chacabuco',1)
INSERT INTO [Consultorios].[dbo].[Provincia] VALUES (3,'Cordillera',1)
INSERT INTO [Consultorios].[dbo].[Provincia] VALUES (4,'Maipo',1)
INSERT INTO [Consultorios].[dbo].[Provincia] VALUES (5,'Melipilla',1)
INSERT INTO [Consultorios].[dbo].[Provincia] VALUES (6,'Talagante',1)

INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (1,'Santiago',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (2,'Independecia',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (3,'Conchalí',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (4,'Huachuraba',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (5,'Recoleta',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (6,'Providencia',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (7,'Vitacura',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (8,'Lo Barnechea',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (9,'Las Condes',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (10,'Ñuñoa',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (11,'La Reina',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (12,'Macul',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (13,'Peñalolén',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (14,'La Florida',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (15,'San Joaquín',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (16,'La Granja',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (17,'La Pintana',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (18,'San Ramón',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (19,'San Miguel',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (20,'La Cisterna',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (21,'El Bosque',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (22,'Pedro Aguirre Cerda',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (23,'Lo Espejo',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (24,'Estacion Central',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (25,'Cerrillos',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (26,'Maipú',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (27,'Quinta Normal',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (28,'Lo Prado',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (29,'Pudahuel',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (30,'Cerro Navía',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (31,'Renca',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (32,'Quilicura',1)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (33,'Colina',2)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (34,'Lampa',2)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (35,'Tiltil',2)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (36,'Puente Alto',3)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (37,'San Jose de Maipo',3)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (38,'Pirque',3)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (39,'San Bernardo',4)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (40,'Buin',4)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (41,'Paine',4)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (42,'Calera de Tango',4)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (43,'Melipilla',5)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (44,'María Pinto',5)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (45,'Curacaví',5)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (46,'Alhué',5)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (47,'San Pedro',5)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (48,'Talagante',6)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (49,'Peñaflor',6)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (50,'Isla de Maipo',6)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (51,'El Monte',4)
INSERT INTO [Consultorios].[dbo].[Comuna] VALUES (52,'Padre Hurtado',4)


INSERT INTO [Consultorios].[dbo].[Consultorio] VALUES (1,19999992,'1',1,'Consutorio mi Duoc')

INSERT INTO [Consultorios].[dbo].[Tipo_Usuario] VALUES (1,'paciente')
INSERT INTO [Consultorios].[dbo].[Tipo_Usuario] VALUES (2,'secretaria')
INSERT INTO [Consultorios].[dbo].[Tipo_Usuario] VALUES (3,'enfermera')
INSERT INTO [Consultorios].[dbo].[Tipo_Usuario] VALUES (4,'medico')
INSERT INTO [Consultorios].[dbo].[Tipo_Usuario] VALUES (5,'administrador')


INSERT INTO [Consultorios].[dbo].[Sector] VALUES (1,'Amarillo')
INSERT INTO [Consultorios].[dbo].[Sector] VALUES (2,'Rojo')
INSERT INTO [Consultorios].[dbo].[Sector] VALUES (3,'Azul')
INSERT INTO [Consultorios].[dbo].[Sector] VALUES (4,'Naranjo')
INSERT INTO [Consultorios].[dbo].[Sector] VALUES (5,'Blanco')

INSERT INTO [Consultorios].[dbo].[Jornada_laboral] VALUES (1,1,1,1,1,1,1,1,1,'Mañana')
INSERT INTO [Consultorios].[dbo].[Jornada_laboral] VALUES (2,1,2,2,3,2,1,2,2,'Raro')
INSERT INTO [Consultorios].[dbo].[Jornada_laboral] VALUES (3,1,1,2,1,1,1,1,2,'Normal')
INSERT INTO [Consultorios].[dbo].[Jornada_laboral] VALUES (4,1,2,1,2,1,0,1,1,'Relajado')
INSERT INTO [Consultorios].[dbo].[Jornada_laboral] VALUES (5,1,2,1,2,1,1,1,3,'Extremo')
INSERT INTO [Consultorios].[dbo].[Jornada_laboral] VALUES (6,1,1,1,1,1,3,1,4,'Emergencia')
INSERT INTO [Consultorios].[dbo].[Jornada_laboral] VALUES (7,1,3,2,1,2,1,1,2,'Tarde')
INSERT INTO [Consultorios].[dbo].[Jornada_laboral] VALUES (8,1,1,1,3,2,2,1,5,'Noche')

INSERT INTO [Consultorios].[dbo].[Nacionalidad] VALUES (1,'Chileno')
INSERT INTO [Consultorios].[dbo].[Nacionalidad] VALUES (2,'Argentino')
INSERT INTO [Consultorios].[dbo].[Nacionalidad] VALUES (3,'Mexicano')
INSERT INTO [Consultorios].[dbo].[Nacionalidad] VALUES (4,'Aleman')
INSERT INTO [Consultorios].[dbo].[Nacionalidad] VALUES (5,'Peruano')
INSERT INTO [Consultorios].[dbo].[Nacionalidad] VALUES (6,'Ruso')
INSERT INTO [Consultorios].[dbo].[Nacionalidad] VALUES (7,'Norcoreano')
INSERT INTO [Consultorios].[dbo].[Nacionalidad] VALUES (8,'Haitiano')

INSERT INTO [Consultorios].[dbo].[Grupo_sanguineo] VALUES (1,'Grupo A')
INSERT INTO [Consultorios].[dbo].[Grupo_sanguineo] VALUES (2,'Grupo B')
INSERT INTO [Consultorios].[dbo].[Grupo_sanguineo] VALUES (3,'Grupo AB')
INSERT INTO [Consultorios].[dbo].[Grupo_sanguineo] VALUES (4,'Grupo O')

INSERT INTO [Consultorios].[dbo].[Rh_sanguineo] VALUES (1,'Negativo')
INSERT INTO [Consultorios].[dbo].[Rh_sanguineo] VALUES (2,'Positivo')

INSERT INTO [Consultorios].[dbo].[Especialidad] VALUES (1,'Medicina General')
INSERT INTO [Consultorios].[dbo].[Especialidad] VALUES (2,'Obtetricia')
INSERT INTO [Consultorios].[dbo].[Especialidad] VALUES (3,'Cirujano')
INSERT INTO [Consultorios].[dbo].[Especialidad] VALUES (4,'Veterinario')

INSERT INTO [Consultorios].[dbo].[Genero] VALUES (1,'Masculino')
INSERT INTO [Consultorios].[dbo].[Genero] VALUES (2,'Femenino')
INSERT INTO [Consultorios].[dbo].[Genero] VALUES (3,'Others')

