//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios de este archivo pueden provocar un comportamiento inesperado y se perderán si
//     el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioWeb.Admin.Paciente
{


    public partial class RegistroPaciente
    {
    }
}
