//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioWeb.ServicioFarmacias {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioFarmacias.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/isMedicamento", ReplyAction="http://tempuri.org/IService1/isMedicamentoResponse")]
        bool isMedicamento(int idMedicamento, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/cantidadMedicamento", ReplyAction="http://tempuri.org/IService1/cantidadMedicamentoResponse")]
        string cantidadMedicamento(int idMedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/cantidadMedicamento2", ReplyAction="http://tempuri.org/IService1/cantidadMedicamento2Response")]
        string cantidadMedicamento2(string idMedicamento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : consultorioWeb.ServicioFarmacias.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<consultorioWeb.ServicioFarmacias.IService1>, consultorioWeb.ServicioFarmacias.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool isMedicamento(int idMedicamento, int cantidad) {
            return base.Channel.isMedicamento(idMedicamento, cantidad);
        }
        
        public string cantidadMedicamento(int idMedicamento) {
            return base.Channel.cantidadMedicamento(idMedicamento);
        }
        
        public string cantidadMedicamento2(string idMedicamento) {
            return base.Channel.cantidadMedicamento2(idMedicamento);
        }
    }
}
