//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consultorioWeb.ServicioFarmaciaFunciona {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://farmacias.org/", ConfigurationName="ServicioFarmaciaFunciona.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cantidadMedicamentoResult del espacio de nombres http://farmacias.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://farmacias.org/cantidadMedicamento", ReplyAction="*")]
        consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoResponse cantidadMedicamento(consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idMedicamento del espacio de nombres http://farmacias.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://farmacias.org/cantidadMedicamento2", ReplyAction="*")]
        consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2Response cantidadMedicamento2(consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://farmacias.org/isMedicamento", ReplyAction="*")]
        bool isMedicamento(int idMedicamento, int cantidad);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cantidadMedicamentoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cantidadMedicamento", Namespace="http://farmacias.org/", Order=0)]
        public consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoRequestBody Body;
        
        public cantidadMedicamentoRequest() {
        }
        
        public cantidadMedicamentoRequest(consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://farmacias.org/")]
    public partial class cantidadMedicamentoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idMedicamento;
        
        public cantidadMedicamentoRequestBody() {
        }
        
        public cantidadMedicamentoRequestBody(int idMedicamento) {
            this.idMedicamento = idMedicamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cantidadMedicamentoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cantidadMedicamentoResponse", Namespace="http://farmacias.org/", Order=0)]
        public consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoResponseBody Body;
        
        public cantidadMedicamentoResponse() {
        }
        
        public cantidadMedicamentoResponse(consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://farmacias.org/")]
    public partial class cantidadMedicamentoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cantidadMedicamentoResult;
        
        public cantidadMedicamentoResponseBody() {
        }
        
        public cantidadMedicamentoResponseBody(string cantidadMedicamentoResult) {
            this.cantidadMedicamentoResult = cantidadMedicamentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cantidadMedicamento2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cantidadMedicamento2", Namespace="http://farmacias.org/", Order=0)]
        public consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2RequestBody Body;
        
        public cantidadMedicamento2Request() {
        }
        
        public cantidadMedicamento2Request(consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://farmacias.org/")]
    public partial class cantidadMedicamento2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idMedicamento;
        
        public cantidadMedicamento2RequestBody() {
        }
        
        public cantidadMedicamento2RequestBody(string idMedicamento) {
            this.idMedicamento = idMedicamento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cantidadMedicamento2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cantidadMedicamento2Response", Namespace="http://farmacias.org/", Order=0)]
        public consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2ResponseBody Body;
        
        public cantidadMedicamento2Response() {
        }
        
        public cantidadMedicamento2Response(consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://farmacias.org/")]
    public partial class cantidadMedicamento2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cantidadMedicamento2Result;
        
        public cantidadMedicamento2ResponseBody() {
        }
        
        public cantidadMedicamento2ResponseBody(string cantidadMedicamento2Result) {
            this.cantidadMedicamento2Result = cantidadMedicamento2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : consultorioWeb.ServicioFarmaciaFunciona.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<consultorioWeb.ServicioFarmaciaFunciona.WebService1Soap>, consultorioWeb.ServicioFarmaciaFunciona.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoResponse consultorioWeb.ServicioFarmaciaFunciona.WebService1Soap.cantidadMedicamento(consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoRequest request) {
            return base.Channel.cantidadMedicamento(request);
        }
        
        public string cantidadMedicamento(int idMedicamento) {
            consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoRequest inValue = new consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoRequest();
            inValue.Body = new consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoRequestBody();
            inValue.Body.idMedicamento = idMedicamento;
            consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamentoResponse retVal = ((consultorioWeb.ServicioFarmaciaFunciona.WebService1Soap)(this)).cantidadMedicamento(inValue);
            return retVal.Body.cantidadMedicamentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2Response consultorioWeb.ServicioFarmaciaFunciona.WebService1Soap.cantidadMedicamento2(consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2Request request) {
            return base.Channel.cantidadMedicamento2(request);
        }
        
        public string cantidadMedicamento2(string idMedicamento) {
            consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2Request inValue = new consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2Request();
            inValue.Body = new consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2RequestBody();
            inValue.Body.idMedicamento = idMedicamento;
            consultorioWeb.ServicioFarmaciaFunciona.cantidadMedicamento2Response retVal = ((consultorioWeb.ServicioFarmaciaFunciona.WebService1Soap)(this)).cantidadMedicamento2(inValue);
            return retVal.Body.cantidadMedicamento2Result;
        }
        
        public bool isMedicamento(int idMedicamento, int cantidad) {
            return base.Channel.isMedicamento(idMedicamento, cantidad);
        }
    }
}
